# Generated by Django 5.2.13 on 2026-04-21 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoidAuthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(help_text='Ed25519 Public Key in Hex format', max_length=64)),
                ('recovery_blob', models.TextField(blank=True, help_text='Encrypted private key for recovery', null=True)),
                ('is_void_secured', models.BooleanField(default=False)),
                ('vetting_period_end', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voidauth_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
