# Generated by Django 5.2.10 on 2026-05-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voidauth', '0002_workstationsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkstationSession',
        ),
    ]
